# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.02.102'

RELEASE_GIT_HEAD = '5c985d54ecba9383bb1d20273d23c20122183f97'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Miragelnk/yt-dlp'

ORIGIN = 'Miragelnk/yt-dlp'

_pkg_version = '2024.12.02.102'
