# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.03.083637'

RELEASE_GIT_HEAD = '672a5c0a966fce06950f7247d2d151cbfd7cbd5d'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Miragelnk/yt-dlp'

ORIGIN = 'Miragelnk/yt-dlp'

_pkg_version = '2024.04.03.083637'
