# Autogenerated by devscripts/update-version.py

__version__ = '2025.02.10.99'

RELEASE_GIT_HEAD = 'a07527ea30314617a43ee18ddd54cc592840fbe2'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Miragelnk/yt-dlp'

ORIGIN = 'Miragelnk/yt-dlp'

_pkg_version = '2025.02.10.99'
